name: Code Review
description: Structured code review workflow for PRs or specific files

args:
  - name: TARGET
    description: PR number or file path to review
    required: true
  - name: FOCUS_AREA
    description: Specific area to focus on (security, performance, style, etc.)
    required: false

steps:
  - name: overview
    prompt: prompts/01-overview.md
  - name: detailed-review
    prompt: prompts/02-detailed-review.md
  - name: summary
    prompt: prompts/03-summary.md
